### ISSUE TITLE
A101 kapıda Bot?

### ISSUE THREAD

**Issue by asuhasoft** [keyiflerolsun/A101AktuelRobot#1]
Merhaba

A101 kapıda için de bir bot yapma düşüceniz var mı? 

Örnek url:
https://www.a101kapida.com/meyve-C0101

**Comment by keyiflerolsun** [comment]
Ürün fiyatları çekimi olarak yapılabilir evet..

Örneğin;

> 🎊 Muz Fiyatı Düştü
> 
> 🗑 ~~xx.xx ₺~~
> ⬇️ **yy.yy ₺**
